name: CI
on:
  push:
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
        - x86-windows
        - aarch64-macos
        - arm-linux-gnueabihf
        - wasm32-freestanding
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Zig
      uses: mlugg/setup-zig@v1
      with:
        version: 0.14.0-dev.1710+8ee52f99c
        mirror: 'https://pkg.machengine.org/zig'
    - name: Build
      run: zig build -Dtarget=${{ matrix.target }}
